CREATE TABLE "PONDEV"."JOB_MASTERS" 
   (	"JOB_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"JOB_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"EXEC_USER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10 BYTE), 
	"START_TIME" DATE DEFAULT sysdate, 
	"END_TIME" DATE, 
	"MESSAGE" VARCHAR2(200 BYTE), 
	 CONSTRAINT "PK_JOB_MASTERS_JOBID" PRIMARY KEY ("JOB_ID") )
	 
CREATE TABLE "PONDEV"."JOB_STEPS" 
   (	"JOB_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STEP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STEP_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"STEP_NOTES" VARCHAR2(200 BYTE), 
	"EXEC_USER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10 BYTE), 
	"START_TIME" DATE DEFAULT sysdate, 
	"END_TIME" DATE, 
	"MESSAGE" VARCHAR2(200 BYTE), 
	 CONSTRAINT "FX_JOB_STEPS_TO_JOB_MASTERS" FOREIGN KEY ("JOB_ID")
	  REFERENCES "PONDEV"."JOB_MASTERS" ("JOB_ID") ON DELETE CASCADE ENABLE
   )
   
 CREATE SEQUENCE  "PONDEV"."SQ_JOB_LOG"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 4617 NOCACHE  NOORDER  CYCLE ;

 CREATE SEQUENCE  "PONDEV"."SQ_JOB_STEP_LOG"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 2520 NOCACHE  NOORDER  CYCLE ;